### ISSUE TITLE
Error at the end of process

### ISSUE THREAD

**Issue by BgoodSoft** [Thertzlor/epub-print-page-approximator#3]
MacOS 12.6.6, Python 3
Thank you for this script very interesting.
It seems to be work until I meet this error and no file have been created:

```
[...]
100.00% Done
Traceback (most recent call last):
  File "/Users/Macintosh/Documents/epub-print-page-approximator-main/page_approximator.py", line 31, in <module>
    processEPUB(args.filepath,args.pages,args.suffix,args.outpath,args.name,args.nonav,args.noncx,args.breakmode,pageMode,tuple(int(x) if x.isnumeric() else x for x in args.tocpages),args.page_map,args.suggest,args.autopage,romans,args.nonlinear,args.unlisted,args.attribute)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Macintosh/Documents/epub-print-page-approximator-main/modules/pageprocessor.py", line 258, in processEPUB
    if processNavigations(epub3Nav,ncxNav,pgLinks,repDict,noNav, noNcX,pageOffset,roman,numList):overrideZip(path,pathProcessor(path,newPath,newName,suffix),repDict,adoMap)
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Macintosh/Documents/epub-print-page-approximator-main/modules/navutils.py", line 20, in processNavigations
    if addLinksToNav(epub3Nav,pgLinks,repDict,pageOffset,roman,numList) == False: return print('Pagination Cancelled') or False
       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Macintosh/Documents/epub-print-page-approximator-main/modules/nodeutils.py", line 87, in addLinksToNav
    oldNav:etree.ElementBase = next((x for x in body.findall('x:nav',xns) if x.get('epub:type') == 'page-list'),None)
                                                ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'findall'
```
Any idea ?
Thanks a lot !

**Comment by Thertzlor** [comment]
Hello,

My first question would be if this error happens with one specific epub file, or with all files in general.
If it's only one file, this error could indicate that the ebook contains an empty or malformed html/xml file.

**Comment by BgoodSoft** [comment]
Hi Thertzlor,
I tried with several Epub which all have been checked with Epubcheck


Le 17 déc. 2024 à 22:41, Thertzlor ***@***.***> a écrit :


Hello,

My first question would be if this error happens with one specific epub file, or with all files in general.
If it's only one file, this error could indicate that the ebook contains an empty or malformed html/xml file.

**Comment by Thertzlor** [comment]
After looking around for a while I managed to come across an epub file that also causes this error for me.
Now that I can reproduce it (which confirms that this is in fact not a platform specific problem), I should be able to fix this pretty soon.

**Comment by Thertzlor** [comment]
The bug that caused the Epub3 Navigation's <body> tag to not be found is now solved in the latest version.

**Comment by BgoodSoft** [comment]
The bug is in evolution. I notice a difference : when I submit an EPUB with page-list existing, it asks me to overwrite Y/N. It didn't that before. 
Here the bug : 

Traceback (most recent call last):
  File "/Users/Macintosh/Documents/TRAVAIL/00_EPUB_TEST/epub-print-page-approximator-main/page_approximator.py", line 31, in <module>
    processEPUB(args.filepath,args.pages,args.suffix,args.outpath,args.name,args.nonav,args.noncx,args.breakmode,pageMode,tuple(int(x) if x.isnumeric() else x for x in args.tocpages),args.page_map,args.suggest,args.autopage,romans,args.nonlinear,args.unlisted,args.attribute)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Macintosh/Documents/TRAVAIL/00_EPUB_TEST/epub-print-page-approximator-main/modules/pageprocessor.py", line 262, in processEPUB
    if processNavigations(epub3Nav,ncxNav,pgLinks,repDict,noNav, noNcX,pageOffset,roman,numList):overrideZip(path,pathProcessor(path,newPath,newName,suffix),repDict,adoMap)
                                                                                                 ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Macintosh/Documents/TRAVAIL/00_EPUB_TEST/epub-print-page-approximator-main/modules/pageprocessor.py", line 23, in overrideZip
    with zipfile.ZipFile(src) as inZip, zipfile.ZipFile(dest, "w",compression=zipfile.ZIP_DEFLATED) as outZip:
                                        ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/zipfile/__init__.py", line 1362, in __init__
    self.fp = io.open(file, filemode)
              ~~~~~~~^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Users/Macintosh/Documents/TRAVAIL/00_EPUB_TEST/epub-print-page-approximator-main/TEST2_paginated.epub'

**Comment by Thertzlor** [comment]
I still haven't managed to reproduce this bug, could it be some mac specific permission issue where it wasn't able to create the output file?

Also could you send the command line arguments you are starting the program with?

**Comment by BgoodSoft** [comment]
This is the command line :

python3 /Users/Macintosh/Documents/epub-print-page-approximator-main/page_approximator.py "/Users/Macintosh/Documents/depub-print-page-approximator-main/TEST2.epub" 100



Le 5 févr. 2025 à 09:05, Thertzlor ***@***.***> a écrit :


I still haven't managed to reproduce this bug, could it be some mac specific permission issue where it wasn't able to create the output file?

Also could you send the command line arguments you are starting the program with?
